/**
 * LLM Content Generation Validation Tests
 * Tests that validate the engine's ability to execute LLM-generated content
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { LLMRTEngineImpl } from './engine';
import { validateCartridge } from './validator';

// Mock window.matchMedia for accessibility manager
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

describe('LLM Content Generation Validation', () => {
  let engine: LLMRTEngineImpl;
  let canvas: HTMLCanvasElement;

  beforeEach(() => {
    canvas = document.createElement('canvas');
    canvas.width = 800;
    canvas.height = 600;
    document.body.appendChild(canvas);

    engine = new LLMRTEngineImpl();
  });

  afterEach(() => {
    engine?.stop();
    document.body.removeChild(canvas);
  });

  describe('Automated LLM Prompt Validation', () => {
    it('should validate simple pong-style game generation', async () => {
      // Simulated LLM-generated cartridge for "Create a simple pong game"
      const llmPongGame = {
        "version": "1.0",
        "metadata": {
          "title": "LLM Pong",
          "author": "AI Assistant",
          "description": "A simple pong game generated by LLM"
        },
        "theme": {
          "colors": {
            "primary": "#ffffff",
            "secondary": "#888888",
            "background": "#000000",
            "text": "#ffffff",
            "accent": "#00ff00"
          },
          "font": {
            "family": "monospace",
            "sizes": {
              "small": 12,
              "medium": 16,
              "large": 24
            }
          },
          "spacing": {
            "small": 4,
            "medium": 8,
            "large": 16
          },
          "radii": {
            "small": 2,
            "medium": 4,
            "large": 8
          }
        },
        "scenes": [
          {
            "id": "game",
            "root": {
              "id": "root",
              "type": "Group",
              "transform": {
                "position": [0, 0],
                "scale": [1, 1],
                "rotation": 0,
                "skew": [0, 0],
                "alpha": 1
              },
              "visible": true,
              "children": [
                {
                  "id": "paddle1",
                  "type": "Sprite",
                  "transform": {
                    "position": [50, 300],
                    "scale": [1, 1],
                    "rotation": 0,
                    "skew": [0, 0],
                    "alpha": 1
                  },
                  "visible": true,
                  "children": [],
                  "actions": [],
                  "triggers": [
                    {
                      "event": "on.key",
                      "key": "w",
                      "actions": [
                        {
                          "type": "tween",
                          "params": {
                            "target": "paddle1",
                            "property": "position.y",
                            "to": "position.y - 20",
                            "duration": 0.1
                          }
                        }
                      ]
                    }
                  ],
                  "sprite": "paddle"
                },
                {
                  "id": "ball",
                  "type": "Sprite",
                  "transform": {
                    "position": [400, 300],
                    "scale": [1, 1],
                    "rotation": 0,
                    "skew": [0, 0],
                    "alpha": 1
                  },
                  "visible": true,
                  "children": [],
                  "actions": [],
                  "triggers": [
                    {
                      "event": "on.start",
                      "actions": [
                        {
                          "type": "setVar",
                          "params": {
                            "name": "ballVelX",
                            "value": 200
                          }
                        },
                        {
                          "type": "setVar",
                          "params": {
                            "name": "ballVelY",
                            "value": 100
                          }
                        }
                      ]
                    }
                  ],
                  "sprite": "ball"
                }
              ],
              "actions": [],
              "triggers": []
            }
          }
        ],
        "assets": {
          "sprites": [
            {
              "id": "paddle",
              "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAoCAYAAAD4lS7qAAAAFklEQVR42mNkYGBgYKAKGFUwqmBUAQAABQABDauqhwAAAABJRU5ErkJggg=="
            },
            {
              "id": "ball",
              "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFklEQVR42mNkYGBgYKAKGFUwqmBUAQAABQABDauqhwAAAABJRU5ErkJggg=="
            }
          ],
          "audio": [],
          "fonts": []
        },
        "variables": {
          "ballVelX": 0,
          "ballVelY": 0,
          "score1": 0,
          "score2": 0
        }
      };

      // Validate the LLM-generated content
      const validation = validateCartridge(llmPongGame);
      if (!validation.valid) {
        console.log('Validation errors for LLM Pong Game:', validation.errors);
      }
      expect(validation.valid).toBe(true);
      expect(validation.errors).toHaveLength(0);

      // Test that it loads and runs
      await engine.loadCartridge(llmPongGame);
      engine.start();

      await new Promise(resolve => setTimeout(resolve, 100));

      const state = engine.getState();
      expect(state.running).toBe(true);
      expect(state.currentScene).toBe('game');
    });

    it('should validate raycast corridor generation', async () => {
      // Simulated LLM-generated cartridge for "Create a 3D corridor using raycasting"
      const llmCorridorGame = {
        "version": "1.0",
        "metadata": {
          "title": "LLM Corridor",
          "author": "AI Assistant",
          "description": "A 3D corridor generated by LLM"
        },
        "theme": {
          "colors": {
            "primary": "#8B4513",
            "secondary": "#654321",
            "background": "#000000",
            "text": "#ffffff",
            "accent": "#ffff00"
          },
          "font": {
            "family": "monospace",
            "sizes": { "small": 12, "medium": 16, "large": 24 }
          },
          "spacing": { "small": 4, "medium": 8, "large": 16 },
          "radii": { "small": 2, "medium": 4, "large": 8 }
        },
        "scenes": [
          {
            "id": "corridor",
            "root": {
              "id": "root",
              "type": "Group",
              "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
              "visible": true,
              "children": [
                {
                  "id": "raycast-map",
                  "type": "Group",
                  "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
                  "visible": true,
                  "children": [],
                  "actions": [],
                  "triggers": [
                    {
                      "event": "on.key",
                      "key": "w",
                      "actions": [
                        {
                          "type": "moveCamera",
                          "params": {
                            "direction": "forward",
                            "speed": 100
                          }
                        }
                      ]
                    }
                  ],
                  "map": [
                    [1, 1, 1, 1, 1],
                    [1, 0, 0, 0, 1],
                    [1, 0, 0, 0, 1],
                    [1, 0, 0, 0, 1],
                    [1, 1, 1, 1, 1]
                  ],
                  "textures": ["wall"],
                  "billboards": [],
                  "fov": 60,
                  "renderDistance": 10
                }
              ],
              "actions": [],
              "triggers": []
            }
          }
        ],
        "assets": {
          "sprites": [
            {
              "id": "wall",
              "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
            }
          ],
          "audio": [],
          "fonts": []
        },
        "variables": {}
      };

      const validation = validateCartridge(llmCorridorGame);
      if (!validation.valid) {
        console.log('Validation errors for LLM Corridor Game:', validation.errors);
      }
      expect(validation.valid).toBe(true);

      await engine.loadCartridge(llmCorridorGame);
      engine.start();

      await new Promise(resolve => setTimeout(resolve, 100));

      const state = engine.getState();
      expect(state.running).toBe(true);
      expect(state.currentScene).toBeDefined();
    });

    it('should validate mode7 racing game generation', async () => {
      // Simulated LLM-generated cartridge for "Create a racing game with Mode-7 graphics"
      const llmRacingGame = {
        "version": "1.0",
        "metadata": {
          "title": "LLM Racer",
          "author": "AI Assistant",
          "description": "A racing game with Mode-7 graphics generated by LLM"
        },
        "theme": {
          "colors": {
            "primary": "#00ff00",
            "secondary": "#008800",
            "background": "#87CEEB",
            "text": "#ffffff",
            "accent": "#ffff00"
          },
          "font": {
            "family": "monospace",
            "sizes": { "small": 12, "medium": 16, "large": 24 }
          },
          "spacing": { "small": 4, "medium": 8, "large": 16 },
          "radii": { "small": 2, "medium": 4, "large": 8 }
        },
        "scenes": [
          {
            "id": "race",
            "root": {
              "id": "root",
              "type": "Group",
              "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
              "visible": true,
              "children": [
                {
                  "id": "ground",
                  "type": "Group",
                  "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
                  "visible": true,
                  "children": [],
                  "actions": [],
                  "triggers": [
                    {
                      "event": "on.key",
                      "key": "a",
                      "actions": [
                        {
                          "type": "tween",
                          "params": {
                            "target": "ground",
                            "property": "rotation",
                            "to": "rotation - 0.1",
                            "duration": 0.1
                          }
                        }
                      ]
                    }
                  ],
                  "texture": "track",
                  "horizon": 0.6,
                  "scale": 2.0,
                  "offset": [0, 0]
                }
              ],
              "actions": [],
              "triggers": []
            }
          }
        ],
        "assets": {
          "sprites": [
            {
              "id": "track",
              "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
            }
          ],
          "audio": [],
          "fonts": []
        },
        "variables": {}
      };

      const validation = validateCartridge(llmRacingGame);
      if (!validation.valid) {
        console.log('Validation errors for LLM Racing Game:', validation.errors);
      }
      expect(validation.valid).toBe(true);

      await engine.loadCartridge(llmRacingGame);
      engine.start();

      await new Promise(resolve => setTimeout(resolve, 100));

      const state = engine.getState();
      expect(state.running).toBe(true);
      expect(state.currentScene).toBeDefined();
    });
  });

  describe('LLM Generation Quality Metrics', () => {
    it('should validate that LLM can generate playable content in single pass', async () => {
      // Test multiple LLM-style generations to ensure consistency
      const generations = [
        // Simple platformer
        {
          "version": "1.0",
          "metadata": { "title": "Simple Jump", "author": "AI", "description": "Jump game" },
          "theme": {
            "colors": { "primary": "#0066cc", "secondary": "#004499", "background": "#87CEEB", "text": "#ffffff", "accent": "#ffff00" },
            "font": { "family": "Arial", "sizes": { "small": 12, "medium": 16, "large": 24 } },
            "spacing": { "small": 4, "medium": 8, "large": 16 },
            "radii": { "small": 2, "medium": 4, "large": 8 }
          },
          "scenes": [{
            "id": "main",
            "root": {
              "id": "root", "type": "Group",
              "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
              "visible": true, "children": [{
                "id": "player", "type": "Sprite",
                "transform": { "position": [100, 500], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
                "visible": true, "children": [], "actions": [],
                "triggers": [{
                  "event": "on.key", "key": "space",
                  "actions": [{ "type": "tween", "params": { "target": "player", "property": "position.y", "to": "position.y - 100", "duration": 0.5 } }]
                }],
                "sprite": "player"
              }], "actions": [], "triggers": []
            }
          }],
          "assets": {
            "sprites": [{ "id": "player", "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==" }],
            "audio": [], "fonts": []
          },
          "variables": {}
        },
        // Particle effect demo
        {
          "version": "1.0",
          "metadata": { "title": "Fireworks", "author": "AI", "description": "Particle effects" },
          "theme": {
            "colors": { "primary": "#ff6600", "secondary": "#cc4400", "background": "#000033", "text": "#ffffff", "accent": "#ffff00" },
            "font": { "family": "Arial", "sizes": { "small": 12, "medium": 16, "large": 24 } },
            "spacing": { "small": 4, "medium": 8, "large": 16 },
            "radii": { "small": 2, "medium": 4, "large": 8 }
          },
          "scenes": [{
            "id": "main",
            "root": {
              "id": "root", "type": "Group",
              "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
              "visible": true, "children": [{
                "id": "fireworks", "type": "Particles2D",
                "transform": { "position": [400, 300], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
                "visible": true, "children": [], "actions": [],
                "triggers": [{ "event": "on.start", "actions": [{ "type": "emit", "params": { "target": "fireworks" } }] }],
                "emitter": {
                  "rate": 50, "lifetime": 3.0, "sprite": "spark",
                  "velocity": { "min": [-200, -200], "max": [200, -50] },
                  "acceleration": [0, 300]
                }
              }], "actions": [], "triggers": []
            }
          }],
          "assets": {
            "sprites": [{ "id": "spark", "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==" }],
            "audio": [], "fonts": []
          },
          "variables": {}
        }
      ];

      let successCount = 0;
      
      for (const generation of generations) {
        try {
          const validation = validateCartridge(generation);
          if (validation.valid) {
            await engine.loadCartridge(generation);
            engine.start();
            
            await new Promise(resolve => setTimeout(resolve, 50));
            
            const state = engine.getState();
            if (state.running) {
              successCount++;
            }
            
            engine.stop();
          }
        } catch (error) {
          // Generation failed
        }
      }

      // Should achieve ≥95% success rate (requirement 2.5)
      const successRate = successCount / generations.length;
      expect(successRate).toBeGreaterThanOrEqual(0.95);
    });

    it('should provide actionable validation errors for common LLM mistakes', async () => {
      // Test common LLM generation mistakes
      const commonMistakes = [
        // Missing required fields
        {
          "version": "1.0",
          "metadata": { "title": "Incomplete" }
          // Missing theme, scenes, assets
        },
        // Invalid node type
        {
          "version": "1.0",
          "metadata": { "title": "Bad Node", "author": "AI", "description": "Test" },
          "theme": {
            "colors": { "primary": "#ff0000", "secondary": "#00ff00", "background": "#000000", "text": "#ffffff", "accent": "#ffff00" },
            "font": { "family": "Arial", "sizes": { "small": 12, "medium": 16, "large": 24 } },
            "spacing": { "small": 4, "medium": 8, "large": 16 },
            "radii": { "small": 2, "medium": 4, "large": 8 }
          },
          "scenes": [{
            "id": "main",
            "root": {
              "id": "root", "type": "InvalidNodeType",
              "transform": { "position": [0, 0], "scale": [1, 1], "rotation": 0, "skew": [0, 0], "alpha": 1 },
              "visible": true, "children": [], "actions": [], "triggers": []
            }
          }],
          "assets": { "sprites": [], "audio": [], "fonts": [] },
          "variables": {}
        }
      ];

      for (const mistake of commonMistakes) {
        const validation = validateCartridge(mistake);
        expect(validation.valid).toBe(false);
        expect(validation.errors.length).toBeGreaterThan(0);
        
        // Errors should be actionable (contain suggestions)
        const hasActionableErrors = validation.errors.some(error => 
          error.suggestion && error.suggestion.length > 0
        );
        expect(hasActionableErrors).toBe(true);
      }
    });
  });
});